extensions:
  commerce/configuration/1:
    $include: src/commerce-configuration-1/ext.config.yaml

  commerce/extensibility/1:
    $include: src/commerce-extensibility-1/ext.config.yaml

  commerce/backend-ui/1:
    $include: src/commerce-backend-ui-1/ext.config.yaml

application:
  actions: actions
  runtimeManifest:
    packages:
      capstone-appbuilder:
        license: Apache-2.0
        actions:
          product-badge:
            function: actions/product-badge/index.js
            web: 'yes'
            runtime: nodejs:22
            include-ims-credentials: true
            inputs:
              LOG_LEVEL: debug
              IMS_OAUTH_S2S_CLIENT_ID: $IMS_OAUTH_S2S_CLIENT_ID
              IMS_OAUTH_S2S_CLIENT_SECRET: $IMS_OAUTH_S2S_CLIENT_SECRET
              IMS_OAUTH_S2S_ORG_ID: $IMS_OAUTH_S2S_ORG_ID
              IMS_OAUTH_S2S_SCOPES: $IMS_OAUTH_S2S_SCOPES
              IMS_TOKEN_URL: $IMS_TOKEN_URL
            annotations:
              require-adobe-auth: false
              final: true
          setup-collections:
            function: actions/setup-collections/index.js
            web: 'yes'
            runtime: nodejs:22
            include-ims-credentials: true
            inputs:
              LOG_LEVEL: debug
              IMS_OAUTH_S2S_CLIENT_ID: $IMS_OAUTH_S2S_CLIENT_ID
              IMS_OAUTH_S2S_CLIENT_SECRET: $IMS_OAUTH_S2S_CLIENT_SECRET
              IMS_OAUTH_S2S_ORG_ID: $IMS_OAUTH_S2S_ORG_ID
              IMS_OAUTH_S2S_SCOPES: $IMS_OAUTH_S2S_SCOPES
              IMS_TOKEN_URL: $IMS_TOKEN_URL
            annotations:
              require-adobe-auth: false
              final: true
          save-badge-rule:
            function: actions/save-badge-rule/index.js
            web: 'yes'
            runtime: nodejs:22
            include-ims-credentials: true
            inputs:
              LOG_LEVEL: debug
              IMS_OAUTH_S2S_CLIENT_ID: $IMS_OAUTH_S2S_CLIENT_ID
              IMS_OAUTH_S2S_CLIENT_SECRET: $IMS_OAUTH_S2S_CLIENT_SECRET
              IMS_OAUTH_S2S_ORG_ID: $IMS_OAUTH_S2S_ORG_ID
              IMS_OAUTH_S2S_SCOPES: $IMS_OAUTH_S2S_SCOPES
              IMS_TOKEN_URL: $IMS_TOKEN_URL
            annotations:
              require-adobe-auth: false
              final: true
          get-badge-rules:
            function: actions/get-badge-rules/index.js
            web: 'yes'
            runtime: nodejs:22
            include-ims-credentials: true
            inputs:
              LOG_LEVEL: debug
              IMS_OAUTH_S2S_CLIENT_ID: $IMS_OAUTH_S2S_CLIENT_ID
              IMS_OAUTH_S2S_CLIENT_SECRET: $IMS_OAUTH_S2S_CLIENT_SECRET
              IMS_OAUTH_S2S_ORG_ID: $IMS_OAUTH_S2S_ORG_ID
              IMS_OAUTH_S2S_SCOPES: $IMS_OAUTH_S2S_SCOPES
              IMS_TOKEN_URL: $IMS_TOKEN_URL
            annotations:
              require-adobe-auth: false
              final: true
          delete-badge-rule:
            function: actions/delete-badge-rule/index.js
            web: 'yes'
            runtime: nodejs:22
            include-ims-credentials: true
            inputs:
              LOG_LEVEL: debug
              IMS_OAUTH_S2S_CLIENT_ID: $IMS_OAUTH_S2S_CLIENT_ID
              IMS_OAUTH_S2S_CLIENT_SECRET: $IMS_OAUTH_S2S_CLIENT_SECRET
              IMS_OAUTH_S2S_ORG_ID: $IMS_OAUTH_S2S_ORG_ID
              IMS_OAUTH_S2S_SCOPES: $IMS_OAUTH_S2S_SCOPES
              IMS_TOKEN_URL: $IMS_TOKEN_URL
            annotations:
              require-adobe-auth: false
              final: true
          get-products:
            function: actions/get-products/index.js
            web: 'yes'
            runtime: nodejs:22
            include-ims-credentials: true
            inputs:
              LOG_LEVEL: debug
              IMS_OAUTH_S2S_CLIENT_ID: $IMS_OAUTH_S2S_CLIENT_ID
              IMS_OAUTH_S2S_CLIENT_SECRET: $IMS_OAUTH_S2S_CLIENT_SECRET
              IMS_OAUTH_S2S_ORG_ID: $IMS_OAUTH_S2S_ORG_ID
              IMS_OAUTH_S2S_SCOPES: $IMS_OAUTH_S2S_SCOPES
              IMS_TOKEN_URL: $IMS_TOKEN_URL
              COMMERCE_API_BASE_URL: $COMMERCE_API_BASE_URL
            annotations:
              require-adobe-auth: false
              final: true
          save-static-assignment:
            function: actions/save-static-assignment/index.js
            web: 'yes'
            runtime: nodejs:22
            include-ims-credentials: true
            inputs:
              LOG_LEVEL: debug
              IMS_OAUTH_S2S_CLIENT_ID: $IMS_OAUTH_S2S_CLIENT_ID
              IMS_OAUTH_S2S_CLIENT_SECRET: $IMS_OAUTH_S2S_CLIENT_SECRET
              IMS_OAUTH_S2S_ORG_ID: $IMS_OAUTH_S2S_ORG_ID
              IMS_OAUTH_S2S_SCOPES: $IMS_OAUTH_S2S_SCOPES
              IMS_TOKEN_URL: $IMS_TOKEN_URL
            annotations:
              require-adobe-auth: false
              final: true
          get-static-assignments:
            function: actions/get-static-assignments/index.js
            web: 'yes'
            runtime: nodejs:22
            include-ims-credentials: true
            inputs:
              LOG_LEVEL: debug
              IMS_OAUTH_S2S_CLIENT_ID: $IMS_OAUTH_S2S_CLIENT_ID
              IMS_OAUTH_S2S_CLIENT_SECRET: $IMS_OAUTH_S2S_CLIENT_SECRET
              IMS_OAUTH_S2S_ORG_ID: $IMS_OAUTH_S2S_ORG_ID
              IMS_OAUTH_S2S_SCOPES: $IMS_OAUTH_S2S_SCOPES
              IMS_TOKEN_URL: $IMS_TOKEN_URL
            annotations:
              require-adobe-auth: false
              final: true
          delete-static-assignment:
            function: actions/delete-static-assignment/index.js
            web: 'yes'
            runtime: nodejs:22
            include-ims-credentials: true
            inputs:
              LOG_LEVEL: debug
              IMS_OAUTH_S2S_CLIENT_ID: $IMS_OAUTH_S2S_CLIENT_ID
              IMS_OAUTH_S2S_CLIENT_SECRET: $IMS_OAUTH_S2S_CLIENT_SECRET
              IMS_OAUTH_S2S_ORG_ID: $IMS_OAUTH_S2S_ORG_ID
              IMS_OAUTH_S2S_SCOPES: $IMS_OAUTH_S2S_SCOPES
              IMS_TOKEN_URL: $IMS_TOKEN_URL
            annotations:
              require-adobe-auth: false
              final: true
          get-badge-catalog:
            function: actions/get-badge-catalog/index.js
            web: 'yes'
            runtime: nodejs:22
            include-ims-credentials: true
            inputs:
              LOG_LEVEL: debug
              IMS_OAUTH_S2S_CLIENT_ID: $IMS_OAUTH_S2S_CLIENT_ID
              IMS_OAUTH_S2S_CLIENT_SECRET: $IMS_OAUTH_S2S_CLIENT_SECRET
              IMS_OAUTH_S2S_ORG_ID: $IMS_OAUTH_S2S_ORG_ID
              IMS_OAUTH_S2S_SCOPES: $IMS_OAUTH_S2S_SCOPES
              IMS_TOKEN_URL: $IMS_TOKEN_URL
            annotations:
              require-adobe-auth: false
              final: true
          get-badge-states:
            function: actions/get-badge-states/index.js
            web: 'yes'
            runtime: nodejs:22
            include-ims-credentials: true
            inputs:
              LOG_LEVEL: debug
              IMS_OAUTH_S2S_CLIENT_ID: $IMS_OAUTH_S2S_CLIENT_ID
              IMS_OAUTH_S2S_CLIENT_SECRET: $IMS_OAUTH_S2S_CLIENT_SECRET
              IMS_OAUTH_S2S_ORG_ID: $IMS_OAUTH_S2S_ORG_ID
              IMS_OAUTH_S2S_SCOPES: $IMS_OAUTH_S2S_SCOPES
              IMS_TOKEN_URL: $IMS_TOKEN_URL
            annotations:
              require-adobe-auth: false
              final: true
          product-event-consumer:
            function: actions/product-event-consumer/index.js
            web: 'no'
            runtime: nodejs:22
            include-ims-credentials: true
            inputs:
              LOG_LEVEL: debug
              IMS_OAUTH_S2S_CLIENT_ID: $IMS_OAUTH_S2S_CLIENT_ID
              IMS_OAUTH_S2S_CLIENT_SECRET: $IMS_OAUTH_S2S_CLIENT_SECRET
              IMS_OAUTH_S2S_ORG_ID: $IMS_OAUTH_S2S_ORG_ID
              IMS_OAUTH_S2S_SCOPES: $IMS_OAUTH_S2S_SCOPES
              IMS_TOKEN_URL: $IMS_TOKEN_URL
              COMMERCE_API_BASE_URL: $COMMERCE_API_BASE_URL
              COMMERCE_STORE_CODE: $COMMERCE_STORE_CODE
            annotations:
              final: true
    database:
      auto-provision: false
      region: amer
